export type ExecutionNetworkPolicy = "none" | "fixed-official-download" | "caller-declared-denied";
export type ExecutionApprovalPolicy =
  | "none"
  | "project-lease"
  | "local-human-control"
  | "external-search-local-approval";

export interface ExecutionCapabilityDefinition {
  capabilityId: string;
  purpose: string;
  platforms: Array<"darwin" | "linux" | "win32">;
  callSites: string[];
  binaryPolicy: string;
  allowedArgvGrammar: string;
  allowedCwdRoot: string;
  allowedReadRoots: string;
  allowedWriteRoots: string;
  networkPolicy: ExecutionNetworkPolicy;
  environmentProfile: string;
  approvalPolicy: ExecutionApprovalPolicy;
  leasePreset: string;
  maxRuntimeMs: number;
  outputPolicy: string;
}

const definitions = [
  {
    capabilityId: "macos-open-chatgpt-images",
    purpose: "Open the fixed ChatGPT Images URL in Safari or Google Chrome without prompt automation.",
    platforms: ["darwin"],
    callSites: ["src/assets/chatgpt-images-app.ts"],
    binaryPolicy: "fixed /usr/bin/open",
    allowedArgvGrammar: "optional fixed browser application selector plus fixed ChatGPT Images URL",
    allowedCwdRoot: "none",
    allowedReadRoots: "none",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "system-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "image-only or stronger",
    maxRuntimeMs: 10_000,
    outputPolicy: "exit status only",
  },
  {
    capabilityId: "macos-image-intake-helper",
    purpose: "Discover and run the local pngpaste helper for clipboard image intake.",
    platforms: ["darwin"],
    callSites: ["src/assets/image-intake.ts"],
    binaryPolicy: "fixed /usr/bin/which followed by resolved pngpaste executable",
    allowedArgvGrammar: "single helper name lookup or single private temporary image path",
    allowedCwdRoot: "selected project root or private temporary directory",
    allowedReadRoots: "macOS clipboard and private temporary image",
    allowedWriteRoots: "private temporary image and selected project image directory",
    networkPolicy: "none",
    environmentProfile: "image-intake-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "image-only or full-write",
    maxRuntimeMs: 10_000,
    outputPolicy: "no helper output; validated image metadata only",
  },
  {
    capabilityId: "cli-runtime-doctor",
    purpose: "Probe fixed local tool versions for the CLI doctor report.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/cli.ts"],
    binaryPolicy: "doctor-owned binary names such as rg and git resolved by the runtime environment",
    allowedArgvGrammar: "fixed --version probes only",
    allowedCwdRoot: "none",
    allowedReadRoots: "executable metadata only",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "doctor-minimal",
    approvalPolicy: "none",
    leasePreset: "none",
    maxRuntimeMs: 5_000,
    outputPolicy: "first version line only",
  },
  {
    capabilityId: "checkpoint-git-operations",
    purpose: "Capture bounded local Git diffs and reverse-apply a user-selected checkpoint.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/state/checkpoints.ts"],
    binaryPolicy: "git executable resolved by the runtime command policy",
    allowedArgvGrammar: "fixed diff argv or fixed apply --reverse argv with patch on stdin",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project Git metadata and working tree",
    allowedWriteRoots: "selected project working tree only during explicit checkpoint restore",
    networkPolicy: "none",
    environmentProfile: "git-checkpoint",
    approvalPolicy: "project-lease",
    leasePreset: "read-only for capture; full-write for restore",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded redacted diff and exit diagnostics",
  },
  {
    capabilityId: "workspace-registry-git-read",
    purpose: "Read branch and dirty-state hints while scanning registered workspace projects.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/workspace/registry.ts"],
    binaryPolicy: "git executable resolved by the runtime command policy",
    allowedArgvGrammar: "fixed rev-parse or status --porcelain argv",
    allowedCwdRoot: "workspace project candidate directory",
    allowedReadRoots: "workspace candidate Git metadata and working tree",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "git-readonly",
    approvalPolicy: "none",
    leasePreset: "none during bounded local workspace scan",
    maxRuntimeMs: 10_000,
    outputPolicy: "branch string and dirty boolean only",
  },
  {
    capabilityId: "code-search-ripgrep-backend",
    purpose: "Run the legacy internal ripgrep search backend with fixed project-scoped argv.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/code/search.ts"],
    binaryPolicy: "resolved rg executable selected by the internal search backend",
    allowedArgvGrammar: "fixed search flags plus query and canonical project root",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root excluding configured secret and generated directories",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "search-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded parsed matches with secret redaction",
  },
  {
    capabilityId: "macos-control-subprocess",
    purpose: "Invoke fixed macOS control helpers and AppleScript commands after desktop-control authorization.",
    platforms: ["darwin"],
    callSites: ["src/control/mac-input.ts"],
    binaryPolicy: "fixed system binaries or bundled signed AX helper",
    allowedArgvGrammar: "typed control operation argv only",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "approved UI target metadata only",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "desktop-control-minimal",
    approvalPolicy: "local-human-control",
    leasePreset: "control",
    maxRuntimeMs: 15_000,
    outputPolicy: "bounded helper JSON and redacted diagnostics",
  },
  {
    capabilityId: "macos-ax-helper-stream",
    purpose: "Run the bundled AX helper with a typed subcommand and JSON payload over stdio.",
    platforms: ["darwin"],
    callSites: ["src/control/mac-input.ts"],
    binaryPolicy: "bundle-relative chatgpt2codex-ax helper",
    allowedArgvGrammar: "single allowlisted subcommand",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "approved accessibility target",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "desktop-control-minimal",
    approvalPolicy: "local-human-control",
    leasePreset: "control",
    maxRuntimeMs: 15_000,
    outputPolicy: "bounded JSON stdout and stderr",
  },
  {
    capabilityId: "e2e-fixed-tool",
    purpose: "Invoke fixed local E2E support binaries such as osascript and screenshot helpers.",
    platforms: ["darwin"],
    callSites: ["src/e2e/local-e2e.ts"],
    binaryPolicy: "fixed absolute system binary selected by E2E implementation",
    allowedArgvGrammar: "implementation-owned argv only",
    allowedCwdRoot: "selected project root or fixed runtime path",
    allowedReadRoots: "selected project and approved localhost target",
    allowedWriteRoots: "project .chatgpt2codex/e2e directory",
    networkPolicy: "none",
    environmentProfile: "e2e-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or stronger",
    maxRuntimeMs: 120_000,
    outputPolicy: "bounded text or screenshot artifact",
  },
  {
    capabilityId: "e2e-project-server-shell",
    purpose: "Start an explicitly guarded project-local development server for E2E verification.",
    platforms: ["darwin"],
    callSites: ["src/e2e/local-e2e.ts"],
    binaryPolicy: "fixed /bin/zsh",
    allowedArgvGrammar: "-lc plus guardShellCommand-approved project command",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root",
    allowedWriteRoots: "selected project root and .chatgpt2codex/e2e logs",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or stronger",
    maxRuntimeMs: 900_000,
    outputPolicy: "project-local log artifact",
  },
  {
    capabilityId: "windows-process-tree-cleanup",
    purpose: "Terminate a timed-out Windows process tree with taskkill.",
    platforms: ["win32"],
    callSites: ["src/exec/command-runner.ts"],
    binaryPolicy: "fixed taskkill.exe system utility",
    allowedArgvGrammar: "/pid numeric /t /f",
    allowedCwdRoot: "none",
    allowedReadRoots: "none",
    allowedWriteRoots: "process table only",
    networkPolicy: "none",
    environmentProfile: "system-minimal",
    approvalPolicy: "none",
    leasePreset: "inherits parent command lease",
    maxRuntimeMs: 10_000,
    outputPolicy: "cleanup status only",
  },
  {
    capabilityId: "allowlisted-project-command",
    purpose: "Run a command discovered from a trusted project manifest with bounded output and timeout.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/command-runner.ts"],
    binaryPolicy: "verified runtime command selected by discovered command ID",
    allowedArgvGrammar: "manifest argv plus caller-provided argument array",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root",
    allowedWriteRoots: "lease and risk-tier dependent selected project paths",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "risk-tier dependent",
    maxRuntimeMs: 900_000,
    outputPolicy: "bounded summaries with optional retained artifact",
  },
  {
    capabilityId: "guarded-project-shell",
    purpose: "Run a project-confined shell command after secret, destructive, and egress guards.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/local-shell.ts"],
    binaryPolicy: "Node shell implementation with shell:true",
    allowedArgvGrammar: "guardShellCommand-approved command string",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root excluding secret-classified paths",
    allowedWriteRoots: "selected project root when write lease is active",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or full-write",
    maxRuntimeMs: 900_000,
    outputPolicy: "redacted bounded summaries with optional retained artifact",
  },
  {
    capabilityId: "managed-rg-installer-subprocess",
    purpose: "Inspect and extract the pinned official ripgrep archive with fixed local utilities.",
    platforms: ["darwin"],
    callSites: ["src/exec/managed-rg-installer.ts"],
    binaryPolicy: "fixed /usr/bin/tar or verified extracted rg binary",
    allowedArgvGrammar: "fixed archive listing, extraction, and --version argv",
    allowedCwdRoot: "private installer temporary directory",
    allowedReadRoots: "downloaded verified archive and installer temporary directory",
    allowedWriteRoots: "managed tools ripgrep version directory and private temporary directory",
    networkPolicy: "fixed-official-download",
    environmentProfile: "installer-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "full-write",
    maxRuntimeMs: 60_000,
    outputPolicy: "version, digest, and bounded installer diagnostics",
  },
  {
    capabilityId: "external-rg-inspect-search",
    purpose: "Verify a single rg executable identity and run project-scoped approved searches.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/rg-capability.ts"],
    binaryPolicy: "absolute executable path verified by owner, mode, version, and SHA-256",
    allowedArgvGrammar: "--version or fixed no-config project search argv",
    allowedCwdRoot: "selected project root for search; binary directory for inspection",
    allowedReadRoots: "selected project root excluding configured skip directories",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "external-search-minimal",
    approvalPolicy: "external-search-local-approval",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded parsed matches and verified binary metadata",
  },
  {
    capabilityId: "git-readonly-argv",
    purpose: "Read local Git repository state through argv-only git invocations.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/git/git.ts"],
    binaryPolicy: "git executable selected by runtime policy or explicit test injection",
    allowedArgvGrammar: "read-only Git subcommands owned by the Git status implementation",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project .git metadata and working tree",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "git-readonly",
    approvalPolicy: "project-lease",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "redacted structured repository status",
  },
] as const satisfies readonly ExecutionCapabilityDefinition[];

export const EXECUTION_CAPABILITIES: readonly ExecutionCapabilityDefinition[] = definitions;

export function executionCapabilityById(capabilityId: string): ExecutionCapabilityDefinition | undefined {
  return EXECUTION_CAPABILITIES.find((definition) => definition.capabilityId === capabilityId);
}
