export type ExecutionNetworkPolicy = "none" | "fixed-official-download" | "caller-declared-denied" | "tailnet-control" | "openai-codex-service";
export type ExecutionApprovalPolicy =
  | "none"
  | "project-lease"
  | "local-human-operation"
  | "local-human-control"
  | "external-search-local-approval";

export interface ExecutionCapabilityDefinition {
  capabilityId: string;
  purpose: string;
  platforms: Array<"darwin" | "linux" | "win32">;
  callSites: string[];
  binaryPolicy: string;
  allowedArgvGrammar: string;
  allowedCwdRoot: string;
  allowedReadRoots: string;
  allowedWriteRoots: string;
  networkPolicy: ExecutionNetworkPolicy;
  environmentProfile: string;
  approvalPolicy: ExecutionApprovalPolicy;
  leasePreset: string;
  maxRuntimeMs: number;
  outputPolicy: string;
}

const definitions = [
  {
    capabilityId: "macos-open-chatgpt-images",
    purpose: "Open the fixed ChatGPT Images URL in Safari or Google Chrome without prompt automation.",
    platforms: ["darwin"],
    callSites: ["src/assets/chatgpt-images-app.ts"],
    binaryPolicy: "fixed /usr/bin/open",
    allowedArgvGrammar: "optional fixed browser application selector plus fixed ChatGPT Images URL",
    allowedCwdRoot: "none",
    allowedReadRoots: "none",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "system-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "image-only or stronger",
    maxRuntimeMs: 10_000,
    outputPolicy: "exit status only",
  },
  {
    capabilityId: "macos-image-intake-helper",
    purpose: "Discover and run the local pngpaste helper for clipboard image intake.",
    platforms: ["darwin"],
    callSites: ["src/assets/image-intake.ts"],
    binaryPolicy: "fixed /usr/bin/which followed by resolved pngpaste executable",
    allowedArgvGrammar: "single helper name lookup or single private temporary image path",
    allowedCwdRoot: "selected project root or private temporary directory",
    allowedReadRoots: "macOS clipboard and private temporary image",
    allowedWriteRoots: "private temporary image and selected project image directory",
    networkPolicy: "none",
    environmentProfile: "image-intake-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "image-only or full-write",
    maxRuntimeMs: 10_000,
    outputPolicy: "no helper output; validated image metadata only",
  },
  {
    capabilityId: "cli-runtime-doctor",
    purpose: "Probe fixed local tool versions for the CLI doctor report.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/cli.ts"],
    binaryPolicy: "doctor-owned binary names such as rg and git resolved by the runtime environment",
    allowedArgvGrammar: "fixed --version probes only",
    allowedCwdRoot: "none",
    allowedReadRoots: "executable metadata only",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "doctor-minimal",
    approvalPolicy: "none",
    leasePreset: "none",
    maxRuntimeMs: 5_000,
    outputPolicy: "first version line only",
  },
  {
    capabilityId: "checkpoint-git-operations",
    purpose: "Capture bounded local Git diffs and reverse-apply a user-selected checkpoint.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/state/checkpoints.ts"],
    binaryPolicy: "git executable resolved by the runtime command policy",
    allowedArgvGrammar: "fixed diff argv or fixed apply --reverse argv with patch on stdin",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project Git metadata and working tree",
    allowedWriteRoots: "selected project working tree only during explicit checkpoint restore",
    networkPolicy: "none",
    environmentProfile: "git-checkpoint",
    approvalPolicy: "project-lease",
    leasePreset: "read-only for capture; full-write for restore",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded redacted diff and exit diagnostics",
  },
  {
    capabilityId: "workspace-registry-git-read",
    purpose: "Read branch and dirty-state hints while scanning registered workspace projects.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/workspace/registry.ts"],
    binaryPolicy: "git executable resolved by the runtime command policy",
    allowedArgvGrammar: "fixed rev-parse or status --porcelain argv",
    allowedCwdRoot: "workspace project candidate directory",
    allowedReadRoots: "workspace candidate Git metadata and working tree",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "git-readonly",
    approvalPolicy: "none",
    leasePreset: "none during bounded local workspace scan",
    maxRuntimeMs: 10_000,
    outputPolicy: "branch string and dirty boolean only",
  },
  {
    capabilityId: "code-search-ripgrep-backend",
    purpose: "Run the legacy internal ripgrep search backend with fixed project-scoped argv.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/code/search.ts"],
    binaryPolicy: "resolved rg executable selected by the internal search backend",
    allowedArgvGrammar: "fixed search flags plus query and canonical project root",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root excluding configured secret and generated directories",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "search-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded parsed matches with secret redaction",
  },
  {
    capabilityId: "macos-control-subprocess",
    purpose: "Invoke fixed macOS control helpers and AppleScript commands after desktop-control authorization.",
    platforms: ["darwin"],
    callSites: ["src/control/mac-input.ts"],
    binaryPolicy: "fixed system binaries or bundled signed AX helper",
    allowedArgvGrammar: "typed control operation argv only",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "approved UI target metadata only",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "desktop-control-minimal",
    approvalPolicy: "local-human-control",
    leasePreset: "control",
    maxRuntimeMs: 15_000,
    outputPolicy: "bounded helper JSON and redacted diagnostics",
  },
  {
    capabilityId: "macos-app-apply-fixed-binaries",
    purpose: "Verify, gracefully hand off, replace, and relaunch the fixed signed ChatGPT To Codex macOS application after local approval.",
    platforms: ["darwin"],
    callSites: ["src/runtime/macos-app-apply.ts"],
    binaryPolicy: "fixed /usr/bin/codesign, /usr/libexec/PlistBuddy, /usr/bin/pgrep, /usr/bin/osascript, /bin/ps, /bin/kill, and /usr/bin/open",
    allowedArgvGrammar: "fixed signature/plist inspection arguments, exact bundle/process/PID values, and fixed /Applications/ChatGPT To Codex.app path",
    allowedCwdRoot: "none",
    allowedReadRoots: "project build/macos/ChatGPT To Codex.app and fixed installed app bundle",
    allowedWriteRoots: "fixed /Applications staging, backup, and ChatGPT To Codex.app paths only",
    networkPolicy: "none",
    environmentProfile: "system-minimal inherited environment with no shell",
    approvalPolicy: "local-human-operation",
    leasePreset: "full-write plus destructive operation approval",
    maxRuntimeMs: 60_000,
    outputPolicy: "bounded code-signing identity, process status, hashes, and rollback result",
  },
  {
    capabilityId: "macos-app-apply-fixed-worker",
    purpose: "Launch the fixed detached macOS application replacement worker after lease and local approval gates succeed.",
    platforms: ["darwin"],
    callSites: ["src/runtime/macos-app-apply-transaction.ts"],
    binaryPolicy: "current verified Node runtime executable only",
    allowedArgvGrammar: "fixed compiled macos-app-apply-worker.js plus private stateDir and validated requestId",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "private app apply receipt and fixed verified project candidate bundle",
    allowedWriteRoots: "private app apply receipt and fixed /Applications ChatGPT To Codex staging, backup, and install paths",
    networkPolicy: "none",
    environmentProfile: "inherits managed runtime identity only for bounded supervisor/runtime handoff verification",
    approvalPolicy: "local-human-operation",
    leasePreset: "full-write plus consumed local destructive-operation approval",
    maxRuntimeMs: 120_000,
    outputPolicy: "no inherited stdio; terminal result is persisted in a 0600 receipt",
  },
  {
    capabilityId: "macos-ax-helper-stream",
    purpose: "Run the bundled AX helper with a typed subcommand and JSON payload over stdio.",
    platforms: ["darwin"],
    callSites: ["src/control/mac-input.ts"],
    binaryPolicy: "bundle-relative chatgpt2codex-ax helper",
    allowedArgvGrammar: "single allowlisted subcommand",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "approved accessibility target",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "desktop-control-minimal",
    approvalPolicy: "local-human-control",
    leasePreset: "control",
    maxRuntimeMs: 15_000,
    outputPolicy: "bounded JSON stdout and stderr",
  },
  {
    capabilityId: "e2e-fixed-tool",
    purpose: "Invoke fixed local E2E support binaries such as osascript and screenshot helpers.",
    platforms: ["darwin"],
    callSites: ["src/e2e/local-e2e.ts"],
    binaryPolicy: "fixed absolute system binary selected by E2E implementation",
    allowedArgvGrammar: "implementation-owned argv only",
    allowedCwdRoot: "selected project root or fixed runtime path",
    allowedReadRoots: "selected project and approved localhost target",
    allowedWriteRoots: "project .chatgpt2codex/e2e directory",
    networkPolicy: "none",
    environmentProfile: "e2e-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or stronger",
    maxRuntimeMs: 120_000,
    outputPolicy: "bounded text or screenshot artifact",
  },
  {
    capabilityId: "e2e-project-server-shell",
    purpose: "Start an explicitly guarded project-local development server for E2E verification.",
    platforms: ["darwin"],
    callSites: ["src/e2e/local-e2e.ts"],
    binaryPolicy: "fixed /bin/zsh",
    allowedArgvGrammar: "-lc plus guardShellCommand-approved project command",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root",
    allowedWriteRoots: "selected project root and .chatgpt2codex/e2e logs",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or stronger",
    maxRuntimeMs: 900_000,
    outputPolicy: "project-local log artifact",
  },
  {
    capabilityId: "windows-process-tree-cleanup",
    purpose: "Terminate a timed-out Windows process tree with taskkill.",
    platforms: ["win32"],
    callSites: ["src/exec/command-runner.ts"],
    binaryPolicy: "fixed taskkill.exe system utility",
    allowedArgvGrammar: "/pid numeric /t /f",
    allowedCwdRoot: "none",
    allowedReadRoots: "none",
    allowedWriteRoots: "process table only",
    networkPolicy: "none",
    environmentProfile: "system-minimal",
    approvalPolicy: "none",
    leasePreset: "inherits parent command lease",
    maxRuntimeMs: 10_000,
    outputPolicy: "cleanup status only",
  },
  {
    capabilityId: "allowlisted-project-command",
    purpose: "Run a command discovered from a trusted project manifest with bounded output and timeout.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/command-runner.ts"],
    binaryPolicy: "verified runtime command selected by discovered command ID",
    allowedArgvGrammar: "manifest argv plus caller-provided argument array",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root",
    allowedWriteRoots: "lease and risk-tier dependent selected project paths",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "risk-tier dependent",
    maxRuntimeMs: 900_000,
    outputPolicy: "bounded summaries with optional retained artifact",
  },
  {
    capabilityId: "guarded-project-shell",
    purpose: "Run a project-confined shell command after secret, destructive, and egress guards.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/local-shell.ts"],
    binaryPolicy: "Node shell implementation with shell:true",
    allowedArgvGrammar: "guardShellCommand-approved command string",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project root excluding secret-classified paths",
    allowedWriteRoots: "selected project root when write lease is active",
    networkPolicy: "caller-declared-denied",
    environmentProfile: "safe-child-env",
    approvalPolicy: "project-lease",
    leasePreset: "tests-only or full-write",
    maxRuntimeMs: 900_000,
    outputPolicy: "redacted bounded summaries with optional retained artifact",
  },
  {
    capabilityId: "managed-rg-installer-subprocess",
    purpose: "Inspect and extract the pinned official ripgrep archive with fixed local utilities.",
    platforms: ["darwin"],
    callSites: ["src/exec/managed-rg-installer.ts"],
    binaryPolicy: "fixed /usr/bin/tar or verified extracted rg binary",
    allowedArgvGrammar: "fixed archive listing, extraction, and --version argv",
    allowedCwdRoot: "private installer temporary directory",
    allowedReadRoots: "downloaded verified archive and installer temporary directory",
    allowedWriteRoots: "managed tools ripgrep version directory and private temporary directory",
    networkPolicy: "fixed-official-download",
    environmentProfile: "installer-minimal",
    approvalPolicy: "project-lease",
    leasePreset: "full-write",
    maxRuntimeMs: 60_000,
    outputPolicy: "version, digest, and bounded installer diagnostics",
  },
  {
    capabilityId: "external-rg-inspect-search",
    purpose: "Verify a single rg executable identity and run project-scoped approved searches.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/rg-capability.ts"],
    binaryPolicy: "absolute executable path verified by owner, mode, version, and SHA-256",
    allowedArgvGrammar: "--version or fixed no-config project search argv",
    allowedCwdRoot: "selected project root for search; binary directory for inspection",
    allowedReadRoots: "selected project root excluding configured skip directories",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "external-search-minimal",
    approvalPolicy: "external-search-local-approval",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "bounded parsed matches and verified binary metadata",
  },
  {
    capabilityId: "tailscale-mobile-approval-serve",
    purpose: "Configure one fixed tailnet-only Tailscale Serve listener for mobile C2CT approval callbacks.",
    platforms: ["darwin"],
    callSites: ["src/exec/mobile-approval.ts"],
    binaryPolicy: "first executable from the fixed Tailscale application/Homebrew candidate list",
    allowedArgvGrammar: "fixed tailscale serve enable/disable argv for HTTPS 8443 proxying only to 127.0.0.1:7980",
    allowedCwdRoot: "none",
    allowedReadRoots: "fixed Tailscale executable metadata only",
    allowedWriteRoots: "Tailscale daemon Serve configuration for HTTPS port 8443 only",
    networkPolicy: "tailnet-control",
    environmentProfile: "system-minimal",
    approvalPolicy: "local-human-operation",
    leasePreset: "full-write plus local operation approval",
    maxRuntimeMs: 10_000,
    outputPolicy: "bounded Tailscale CLI stdout/stderr retained only on failure",
  },
  {
    capabilityId: "git-readonly-argv",
    purpose: "Read local Git repository state through argv-only git invocations.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/git/git.ts", "src/runtime/runtime-manifest.ts"],
    binaryPolicy: "git executable selected by runtime policy or explicit test injection",
    allowedArgvGrammar: "read-only Git subcommands owned by the Git status implementation",
    allowedCwdRoot: "selected project root",
    allowedReadRoots: "selected project .git metadata and working tree",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "git-readonly",
    approvalPolicy: "project-lease",
    leasePreset: "read-only or stronger",
    maxRuntimeMs: 30_000,
    outputPolicy: "redacted structured repository status",
  },
  {
    capabilityId: "scheduled-goal-codex-worker",
    purpose: "Launch one verified local Codex worker for a pre-authorized bounded scheduled-goal cycle.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/exec/scheduled-goal-runtime.ts"],
    binaryPolicy: "locally resolved absolute executable from fixed Codex installation candidates or an operator-owned absolute executable override that passes file and execute checks",
    allowedArgvGrammar: "fixed codex exec argv for gpt-5.6-luna with ephemeral workspace-write sandbox, canonical --cd project root, private output schema/result paths, and JSON output",
    allowedCwdRoot: "canonical selected project root",
    allowedReadRoots: "selected project root plus private scheduled-goal operation schema and state",
    allowedWriteRoots: "selected project working tree plus private scheduled-goal receipts and bounded result JSON",
    networkPolicy: "openai-codex-service",
    environmentProfile: "minimal HOME/CODEX_HOME/PATH/TMPDIR/locale allowlist",
    approvalPolicy: "local-human-operation",
    leasePreset: "full-write plus a pre-authorized scheduled-goal envelope",
    maxRuntimeMs: 24 * 60 * 60 * 1_000,
    outputPolicy: "subprocess stdout/stderr are drained without retention; only private receipts and validated bounded result JSON are retained",
  },
  {
    capabilityId: "runtime-apply-fixed-worker",
    purpose: "Launch the fixed out-of-process runtime replacement worker after project lease and local operation approval gates succeed.",
    platforms: ["darwin"],
    callSites: ["src/runtime/runtime-apply.ts"],
    binaryPolicy: "current verified Node runtime executable only",
    allowedArgvGrammar: "fixed compiled runtime-apply-worker.js plus stateDir, operationId, and numeric loopback port",
    allowedCwdRoot: "runtime bundle",
    allowedReadRoots: "private runtime update receipts and verified managed runtime roots",
    allowedWriteRoots: "private runtime update receipts, active-runtime pointer, runtime-reload-request marker, and bounded runtime-apply-maintenance marker only",
    networkPolicy: "none",
    environmentProfile: "inherits current runtime identity solely for supervisor/tunnel preservation comparison",
    approvalPolicy: "project-lease",
    leasePreset: "full-write plus consumed local destructive-operation approval",
    maxRuntimeMs: 120_000,
    outputPolicy: "no inherited stdio; progress and terminal result are persisted in a 0600 receipt",
  },
  {
    capabilityId: "runtime-snapshot-process-inventory",
    purpose: "Read the local process command table so automatic runtime retention never removes a snapshot still referenced by a running process.",
    platforms: ["darwin", "linux", "win32"],
    callSites: ["src/runtime/runtime-snapshot-retention.ts"],
    binaryPolicy: "fixed /bin/ps on macOS, fixed /bin/ps or /usr/bin/ps on Linux, or validated SystemRoot PowerShell on Windows",
    allowedArgvGrammar: "fixed process command-line listing arguments only",
    allowedCwdRoot: "none",
    allowedReadRoots: "local process command table only",
    allowedWriteRoots: "none",
    networkPolicy: "none",
    environmentProfile: "fixed locale plus SystemRoot/temp allowlist with no PATH lookup or shell",
    approvalPolicy: "none",
    leasePreset: "none during bounded local runtime retention",
    maxRuntimeMs: 5_000,
    outputPolicy: "command lines remain internal; only matching runtime snapshot roots affect protection metadata",
  },
] as const satisfies readonly ExecutionCapabilityDefinition[];

export const EXECUTION_CAPABILITIES: readonly ExecutionCapabilityDefinition[] = definitions;

export function executionCapabilityById(capabilityId: string): ExecutionCapabilityDefinition | undefined {
  return EXECUTION_CAPABILITIES.find((definition) => definition.capabilityId === capabilityId);
}
