export type OutputPolicyMode = "quiet" | "verbose";

export interface OutputPolicySnapshot {
  mode: OutputPolicyMode;
  showIntermediateCommentary: boolean;
  exceptions: readonly ["approval", "blocker", "error"];
  finalSummary: "concise";
  instruction: string;
  revision: number;
  updatedAt: number;
  source: "startup-env" | "local-control" | "test";
}

const FINALIZATION_INSTRUCTION = [
  "Final response rule: end with exactly three concise summary lines.",
  "Approval fast-path: when a protected operation returns a pending ChatGPT approval with presentApprovalWith, call that direct named presenter immediately as the very next tool call before status polling, extra commentary, or any final response. If that presenter network-fails before render, retry only the presenter; never recreate or replay the protected operation. Use the stated direct fallback presenter only when the host catalog rejects the primary presenter.",
  "Approval-chain rule: when a protected C2CT confirmation or approval card resolves and the already-known next step requires another protected operation or approval card, do not end the assistant turn with an acknowledgement. Read only the exact resolution/status evidence required for that protected card, then immediately invoke the next planned protected operation in the same assistant turn. Continue this chain until the workflow is terminal, a real blocker/error occurs, or a new user decision is genuinely required.",
  "Harmless-probe continuation rule: when the short user message was generated by chatgpt_consent_probe and its exact requestId is already known from the immediately preceding tool result, call chatgpt_consent_probe_status for that exact requestId before any acknowledgement or mutation. If it reports allowed, continue the already-established concrete objective immediately in the same assistant turn. If it reports pending, denied, expired, or missing, fail closed and do not guess or replay a mutation.",
  "Dedicated continuation-resume rule: use chatgpt_continuation_resume only for a dedicated C2CT continuation mechanism that explicitly established hidden continuation state and whose contract requires resume. Do not apply this rule to ordinary Widget Shell choice buttons.",
  "Post-success continuation rule: a successful operation is not workflow completion when a concrete verification, catalog/schema rebind check, post-apply health check, publication check, E2E proof, or other already-known follow-up remains. Treat any result with assistantMayFinalize=false or turnContinuationRequired=true as mechanically non-terminal: follow its turnContinuationAction in the same turn when possible, or render a continuation button if a new user turn is the intended boundary.",
  "Final-prose consistency rule: never state or introduce a concrete next step, remaining verification, required follow-up, or unresolved check in final prose unless it was completed in the same turn or a continuation button was already rendered. A stale or non-current schema-recovery diagnostic must not create follow-up by itself; when the recovery reason says the latest schema-changing apply is not the current runtime, do not invent catalog-refresh work solely from a false or null rebind field.",
  "User-choice card rule: when the next step genuinely requires the user to report or choose among a finite set of 2-5 concrete options, render a chatgpt_widget_shell choice card and immediately call the direct named chatgpt_widget_lab_presenter instead of asking the same question only in prose. Use short natural option labels that mirror the real decision, for example '팝업 떴음' / '팝업 안떴음', '성공' / '실패', or concrete alternatives. Do not use a choice card when free-form explanation, secret input, safety approval, or protected-operation approval is required; those keep their dedicated surfaces.",
  "Widget-choice input rule: a Widget Shell button is only an input UI shortcut. Treat the selected option exactly as if the user typed or sent that option's intent in the chat. For example, clicking '계속 진행하기' means '계속 진행': continue the already-known next work from conversation context. Do not call chatgpt_widget_shell_result or chatgpt_continuation_resume solely because the input came from a Widget Shell button, and do not require hidden continuation persistence, receipt recovery, or a continuation objective for ordinary choice buttons.",
  "Continuation-button rule: if meaningful next work remains and no approval, blocker, or error is waiting on the user, render chatgpt_widget_shell with compact=true and exactly one option whose id is 'continue' and label is '계속 진행하기', then immediately call the direct named chatgpt_widget_lab_presenter in the same turn. The button replaces asking the user to type '계속 진행'; it does not create a hidden workflow dependency. A shell call is incomplete until the presenter succeeds; if presenter rendering fails, retry only the presenter and never recreate the card. Do not render a continuation button when the task is complete or a real user decision beyond continue/stop is required.",
  "Never use c2ct_invoke to render a Widget Shell card or any approval presenter.",
] .join(" ");

const QUIET_INSTRUCTION =
  "Keep tool-by-tool chatter hidden, but do not leave the user staring at a silent 'thinking' state during multi-step C2CT work. Emit one short user-visible progress heartbeat before the first substantive project operation, then only when the work changes phase (for example inspect -> edit -> verify/apply) or after roughly 20-30 seconds / 4-6 consecutive C2CT calls without visible text. Use one compact sentence such as '관련 코드 확인 중…', '수정 반영 중…', or '검증 중…'. Do not enumerate tool names or repeat tool results. Approval, blocker, and error messages remain immediately visible. " + FINALIZATION_INSTRUCTION;

const VERBOSE_INSTRUCTION =
  "Intermediate commentary is allowed when it materially helps the user follow the work. Keep it concise and avoid repeating tool results. Approval, blocker, error, and final completion messages remain visible. " + FINALIZATION_INSTRUCTION;

let revision = 1;
let state: OutputPolicySnapshot = snapshot(
  process.env.CHATGPT2CODEX_SHOW_INTERMEDIATE_COMMENTARY === "1",
  "startup-env",
);

function snapshot(
  showIntermediateCommentary: boolean,
  source: OutputPolicySnapshot["source"],
): OutputPolicySnapshot {
  return Object.freeze({
    mode: showIntermediateCommentary ? "verbose" : "quiet",
    showIntermediateCommentary,
    exceptions: Object.freeze(["approval", "blocker", "error"] as const),
    finalSummary: "concise" as const,
    instruction: showIntermediateCommentary ? VERBOSE_INSTRUCTION : QUIET_INSTRUCTION,
    revision,
    updatedAt: Date.now(),
    source,
  });
}

export function currentOutputPolicy(): OutputPolicySnapshot {
  return state;
}

export function setOutputPolicy(
  showIntermediateCommentary: boolean,
  source: OutputPolicySnapshot["source"] = "local-control",
): OutputPolicySnapshot {
  if (state.showIntermediateCommentary === showIntermediateCommentary && state.source === source) {
    return state;
  }
  revision += 1;
  state = snapshot(showIntermediateCommentary, source);
  return state;
}
