export type OutputPolicyMode = "quiet" | "verbose";

export interface OutputPolicySnapshot {
  mode: OutputPolicyMode;
  showIntermediateCommentary: boolean;
  exceptions: readonly ["approval", "blocker", "error"];
  finalSummary: "concise";
  instruction: string;
  revision: number;
  updatedAt: number;
  source: "startup-env" | "local-control" | "test";
}

export interface OutputPolicyReference {
  mode: OutputPolicyMode;
  showIntermediateCommentary: boolean;
  revision: number;
  referenceOnly: true;
}

export type OutputPolicyEnvelope = OutputPolicySnapshot | OutputPolicyReference;

const FINALIZATION_INSTRUCTION = [
  "Final response rule: end with exactly three concise summary lines.",
  "Approval fast-path: when a protected operation returns a pending ChatGPT approval with presentApprovalWith, call that direct named presenter immediately as the very next tool call before status polling, extra commentary, or any final response. If that presenter network-fails before render, retry only the presenter; never recreate or replay the protected operation. Use the stated direct fallback presenter only when the host catalog rejects the primary presenter.",
  "Approval-chain rule: when a protected C2CT confirmation or approval card resolves and the already-known next step requires another protected operation or approval card, do not end the assistant turn with an acknowledgement. Read only the exact resolution/status evidence required for that protected card, then immediately invoke the next planned protected operation in the same assistant turn. Continue this chain until the workflow is terminal, a real blocker/error occurs, or a new user decision is genuinely required.",
  "Harmless-probe continuation rule: when the short user message was generated by chatgpt_consent_probe and its exact requestId is already known from the immediately preceding tool result, call chatgpt_consent_probe_status for that exact requestId before any acknowledgement or mutation. If it reports allowed, continue the already-established concrete objective immediately in the same assistant turn. If it reports pending, denied, expired, or missing, fail closed and do not guess or replay a mutation.",
  "Dedicated continuation-resume rule: use chatgpt_continuation_resume only for a dedicated protected-operation approval continuation that was explicitly established by the immediately preceding approval flow. A short user message such as '계속 진행' or '고고' is never by itself evidence that such state exists. Do not apply this rule to ordinary Widget Shell choice buttons.",
  "Permission-denied recovery rule: PERMISSION_DENIED describes the exact call, capability, approval, session, project, or tool surface that was refused; it is not by itself proof that the user's whole objective is forbidden or that C2CT must no longer be used. Never blindly replay the same protected or mutating call. First classify the denial from returned details and the live contract. If it is an explicit user denial, security/policy block, or cross-session/cross-project ownership boundary with no supported recovery, stop that exact path and explain the boundary. If it is a capability preset/purpose mismatch, stale or wrong tool surface, session/catalog mismatch, or another recoverable routing problem, follow the returned recommendedAction/recommendedTool/status path or use bounded read-only diagnostics, then continue the original objective in the same turn when safe. If the cause is unclear, inspect connection_status plus the exact lane/operation/status/schema evidence once before deciding. In user-visible prose, briefly say what path was denied, whether the overall objective is still viable, and what safe recovery action is being taken; do not convert a generic PERMISSION_DENIED into a blanket 'stop using C2CT' conclusion.",
  "Connection-recovery continuation rule: a recoverable C2CT connection failure is not a user blocker. When connection_status reports recoveryClassification.continueOriginalGoal=true with boundedRecoveryRecommended=true, treat assistantMayFinalize=false / turnContinuationRequired=true as mechanically non-terminal, follow turnContinuationAction, perform bounded connection recovery, and continue the already-established objective without asking the user for '고고'. Never blindly replay a protected or mutating call; if requestReachedServer or dispatchStarted is true or unknown for a mutation, inspect the exact persisted receipt/status first. Do not restart the runtime when runtimeRestartRecommended=false.",
  "Connection-recovery grace rule: use recoveryClassification.recoveryWindow as the bounded wait contract. The maximum grace is 90 seconds. If routeRecovered=true or recheckAfterMs=0, continue immediately. Otherwise wait no longer than recheckAfterMs before one status recheck, emit at most one concise recovery heartbeat while waiting, and stop the automatic recovery path when exhausted=true. Grace expiry is not permission to restart runtime or replay a mutation; follow the returned recommendedAction.",
  "Connection-recovery tool-class rule: when failedTool is supplied, follow recoveryClassification.evidence.toolRecoveryPolicy. Read-only calls may be reissued only after route recovery; presentation failures retry only the exact presenter after route recovery and never recreate/replay the protected operation; capability acquisition must reconcile current capability state before reacquiring; ordinary mutations require status/receipt reconciliation before any new action; critical mutations use persisted status only and must not be replayed after dispatch. blindReplayAllowed=false is authoritative for every class.",
  "Lane response-loss rule: if failedTool=project_lane_open and requestReachedServer=false or dispatchStarted=false, no lane mutation reached execution, so after route recovery a fresh project_lane_open may proceed. If dispatchStarted=true or the lane handle may have been lost, do not guess or open another privileged lane; use recoveryClassification.evidence.toolRecoveryFirst=project_lane_recover to reconcile this session's own lost-handle lane, then open one fresh lane. Never use project_lane_status when the raw workLaneId was never received.",
  "Post-success continuation rule: a successful operation is not workflow completion when a concrete verification, catalog/schema rebind check, post-apply health check, publication check, E2E proof, or other already-known follow-up remains. Treat any result with assistantMayFinalize=false or turnContinuationRequired=true as mechanically non-terminal: follow its turnContinuationAction in the same turn when possible, or render a continuation button if a new user turn is the intended boundary.",
  "Manual Settings-refresh handoff rule: when runtime_apply_status reports [REDACTED]true and presentManualRefreshWith=chatgpt_manual_refresh_presenter_v1, call that direct named presenter immediately in the same turn. Do not auto-refresh the ChatGPT host catalog and do not replace the presenter with prose. When the user presses 새로고침 완료, that means the Settings refresh is already complete: never call chatgpt_catalog_refresh or npm catalog-refresh afterward. Go directly to the allowlisted npm:chatgpt:c2ct:scan-tools command exactly once for the current project. If that command requires approval, render its dedicated operation approval presenter immediately. The approval card observes the exact approved operation to terminal and the terminal continuation carries the authoritative operation identity/output reference, so the normal approved terminal path must not add a model operation_status call and must never replay command_run. Use operation_status by approvalRequestId only for an active fallback, observer failure, reconnect/response loss, diagnostics, manual inspection, approval recovery, or UNKNOWN reconciliation; read outputRef with output_read using the same approvalRequestId binding when needed so lane transitions cannot orphan the result.",
  "Catalog host-reentry rule: after scan-tools succeeds and reports currentChatRebindProbeRequired=true with currentChatRebindProbeTool matching the expected live generation marker, do not refresh or scan again and do not classify the workflow complete. Immediately render the direct named chatgpt_catalog_reentry_presenter_v1 with that exact expectedMarkerTool. The intended normal flow is therefore runtime apply -> manual Settings refresh -> 완료 -> scan-tools exact operation -> terminal/output recovery -> @C2CT copy/re-entry card. The user must send the exact native @C2CT tool mention in the same chat; assistant-authored @C2CT text, a Widget Shell synthetic follow-up, or c2ct_invoke is not equivalent to host re-entry. On the following native @C2CT user turn, invoke expectedMarkerTool directly by its named surface; only direct marker success clears the rebind follow-up.",
  "Final-prose consistency rule: never state or introduce a concrete next step, remaining verification, required follow-up, or unresolved check in final prose unless it was completed in the same turn or a continuation button was already rendered. A stale or non-current schema-recovery diagnostic must not create follow-up by itself; when the recovery reason says the latest schema-changing apply is not the current runtime, do not invent catalog-refresh work solely from a false or null rebind field.",
  "User-choice card rule: when the next step genuinely requires the user to report or choose among a finite set of 2-5 concrete options, render a chatgpt_widget_shell choice card and immediately call the direct named chatgpt_consent_probe instead of asking the same question only in prose. The Widget Capability Lab presenter is Lab-only and must never be used for Widget Shell cards. Use short natural option labels that mirror the real decision, for example '팝업 떴음' / '팝업 안떴음', '성공' / '실패', or concrete alternatives. Do not use a choice card when free-form explanation, secret input, safety approval, or protected-operation approval is required; those keep their dedicated surfaces.",
  "Widget-choice input rule: a Widget Shell button is only an input UI shortcut. Treat the selected option exactly as if the user typed or sent that option's intent in the chat. For example, clicking '계속 진행하기' means the user directly asked to continue the already-known next work. Start that next tool/action in the same assistant turn whenever possible. Do not call chatgpt_widget_shell_result or chatgpt_continuation_resume solely because the input came from a Widget Shell button, and do not require hidden continuation persistence, receipt recovery, or a continuation objective for ordinary choice buttons.",
  "Continuation-button rule: if meaningful next work remains and no approval, blocker, or error is waiting on the user, render chatgpt_widget_shell with compact=true and exactly one option whose id is 'continue' and label is '계속 진행하기', then immediately call the direct named chatgpt_consent_probe in the same turn. The button replaces asking the user to type '계속 진행'; it does not create a hidden workflow dependency. After the user selects it, keep executing the established objective until terminal success, a real blocker/error, a protected approval, or a genuinely new user decision. Do not stop merely to acknowledge the click or inspect a continuation receipt. A shell call is incomplete until the presenter succeeds; if presenter rendering fails, retry only the presenter and never recreate the card. Do not render a continuation button when the task is complete or a real user decision beyond continue/stop is required.",
  "Never use c2ct_invoke to render a Widget Shell card or any approval presenter.",
] .join(" ");

const PHASE_BOUNDARY_INSTRUCTION =
  "When substantive tool work continues across a real work-phase change (for example inspect/analysis -> edit -> verify/apply/recovery), treat that change as a user-visible boundary: emit one short, truthful assistant commentary immediately before the first tool call of the new phase, even when the previous heartbeat was recent. Keep consecutive calls within the same phase quiet so the host may group them naturally. Approval, blocker, and error surfaces already form visible boundaries, so do not add duplicate commentary around them. Describe only observable work such as '관련 코드 확인 중…', '수정 반영 중…', '검증 중…', or '복구 확인 중…'; never claim model-internal thinking or use '생각중…' as if C2CT could observe it. Do not create empty messages, no-op/separator tools, or synthetic conversation turns merely to force a visual split. ";

const QUIET_INSTRUCTION =
  "Keep tool-by-tool chatter hidden, but do not leave the user staring at a silent 'thinking' state during multi-step C2CT work. Emit one short user-visible progress heartbeat before the first substantive project operation. " + PHASE_BOUNDARY_INSTRUCTION + "When no real phase change occurs, use roughly 20-30 seconds / 4-6 consecutive C2CT calls without visible text only as a fallback heartbeat cadence. Do not enumerate tool names or repeat tool results. " + FINALIZATION_INSTRUCTION;

const VERBOSE_INSTRUCTION =
  "Intermediate commentary is allowed when it materially helps the user follow the work. Keep it concise and avoid repeating tool results. " + PHASE_BOUNDARY_INSTRUCTION + "Approval, blocker, error, and final completion messages remain visible. " + FINALIZATION_INSTRUCTION;

let revision = 1;
let state: OutputPolicySnapshot = snapshot(
  process.env.CHATGPT2CODEX_SHOW_INTERMEDIATE_COMMENTARY === "1",
  "startup-env",
);

function snapshot(
  showIntermediateCommentary: boolean,
  source: OutputPolicySnapshot["source"],
): OutputPolicySnapshot {
  return Object.freeze({
    mode: showIntermediateCommentary ? "verbose" : "quiet",
    showIntermediateCommentary,
    exceptions: Object.freeze(["approval", "blocker", "error"] as const),
    finalSummary: "concise" as const,
    instruction: showIntermediateCommentary ? VERBOSE_INSTRUCTION : QUIET_INSTRUCTION,
    revision,
    updatedAt: Date.now(),
    source,
  });
}

export function currentOutputPolicy(): OutputPolicySnapshot {
  return state;
}

export function currentOutputPolicyReference(): OutputPolicyReference {
  return Object.freeze({
    mode: state.mode,
    showIntermediateCommentary: state.showIntermediateCommentary,
    revision: state.revision,
    referenceOnly: true as const,
  });
}

export function outputPolicyForTool(tool: string): OutputPolicyEnvelope {
  // The bootstrap/contract surfaces carry the complete policy text. Ordinary
  // tool results only need a revision-bearing reference so the same multi-KB
  // instruction is not retransmitted on every read/edit/status call.
  return tool === "connection_status" || tool === "agent_guide"
    ? currentOutputPolicy()
    : currentOutputPolicyReference();
}

export function setOutputPolicy(
  showIntermediateCommentary: boolean,
  source: OutputPolicySnapshot["source"] = "local-control",
): OutputPolicySnapshot {
  if (state.showIntermediateCommentary === showIntermediateCommentary && state.source === source) {
    return state;
  }
  revision += 1;
  state = snapshot(showIntermediateCommentary, source);
  return state;
}
